[build]
target = "riscv32ec-unknown-none-elf.json"

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
#runner = "wlink -v flash --enable-sdi-print"
runner = "wlink flash --enable-sdi-print"

[unstable]
build-std = ["core"] # , "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv32ec-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tlink-qkv2.x",
  "-C", "link-arg=-Map=target/ch32v003.map",
  "--cfg", "portable_atomic_unsafe_assume_single_core",
]
